In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import random

In [3]:
from random import randint

In [4]:
import keras

Using TensorFlow backend.


In [5]:
class env:
        
    def __init__(self, size, step_limit):
        self.number_of_resources = 3
        self.amount_of_resource = 4
        
        self.size = size
        self.step_limit = step_limit
        
        self.initialize_map()
        self.rand_initialize_resources()
        
        self.valid_moves = ['up', 'down', 'left', 'right', 'pass']
    
    def initialize_map(self):
        self.map = np.zeros((self.size, self.size), dtype=int)
        agent_rand_loc = randint(0,1)
        if agent_rand_loc:
            self.agent_1 = [0,self.size -1]
            self.map[0,self.size -1 ] = -1
            self.agent_2 = [0,0]
            self.map[0, 0] = -2
            
        else:
            self.agent_1 = [0,0]
            self.map[0,0] = -1
            self.agent_2 = [0,self.size-1]
            self.map[0,self.size-1] = -2
        
    def rand_initialize_resources(self):
        index = [i for i in range(self.size**2) if (i != 0) and (i != self.size)]
        all_indexes = random.sample(index, self.number_of_resources*self.amount_of_resource)
        res_ind = []
        for i in range(self.number_of_resources):
            resource = random.sample(all_indexes, self.amount_of_resource)
            all_indexes = [r for r in all_indexes if r not in resource]
            resource = [(int(r/self.size),r%self.size) for r in resource]
            for ind in range(len(resource)):
                x, y = resource[ind][0], resource[ind][1]
                self.map[x, y] = i+1
                
    def update(self, move):
        if move not in self.valid_moves:
            print('icorrect move')
        else:
            print('correct move')

Nom agent

In [6]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(64, input_shape=(64, )))
model.add(keras.layers.Activation("elu"))
model.add(keras.layers.Dense(5, input_shape=(64, )))
model.add(keras.layers.Activation("softmax"))
model.compile(optimizer="adam", loss="categorical_crossentropy")

Instructions for updating:
Colocations handled automatically by placer.


Training loop

In [7]:
episodes = 100

environment = env(8, 20)

update_rate = 10

buffer = []
batch_size = 10


for i in range(episodes):
    environment = env(8, 20)
    s = environment.map.reshape((1, 64))
    
    for steps in range(20):
        action = model.predict_classes(s)
        environment.update(environment.valid_moves[int(action)])
        new_s = environment.map.reshape((1, 64))
        buffer.append(np.concatenate([s.reshape(64), action, new_s.reshape(64)]))
        s = np.copy(new_s)
        
        if (i + 1) % update_rate == 0 and batch_size <= len(buffer):
            choices = np.random.choice(len(buffer), batch_size)
            batch = np.array(buffer)[choices]
            #update(model, batch)

correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move
correct move

In [8]:
s

array([[-1,  0,  0,  2,  0,  0,  0, -2,  0,  3,  0,  2,  3,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  3,  0,  1,
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  3,  0,  1,  0,  1,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0]])

In [9]:
buffer

[array([-1,  1,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  2,  3,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,
         0,  1,  2,  0,  0,  0,  0,  0,  3,  0,  0,  0,  3,  0, -1,  1,  0,
         0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  2,  3,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  1,  2,
         0,  0,  0,  0,  0,  3,  0,  0,  0,  3], dtype=int64),
 array([-1,  1,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  2,  3,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,
         0,  1,  2,  0,  0,  0,  0,  0,  3,  0,  0,  0,  3,  0, -1,  1,  0,
         0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  2,  3,  

In [10]:
model.predict_classes(s)

array([3], dtype=int64)